# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/loms/Qt_project/PVD_v2/PVD_gui.ui'
#
# Created: Sun Jul 13 20:06:24 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(583, 505)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/blue-vlc_2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_title = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_title.setText(_fromUtf8(""))
        self.lineEdit_title.setReadOnly(True)
        self.lineEdit_title.setObjectName(_fromUtf8("lineEdit_title"))
        self.horizontalLayout.addWidget(self.lineEdit_title)
        self.horizontalLayout_9.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButton_start = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(13)
        sizePolicy.setHeightForWidth(self.pushButton_start.sizePolicy().hasHeightForWidth())
        self.pushButton_start.setSizePolicy(sizePolicy)
        self.pushButton_start.setMinimumSize(QtCore.QSize(0, 44))
        self.pushButton_start.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/1.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_start.setIcon(icon1)
        self.pushButton_start.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_start.setObjectName(_fromUtf8("pushButton_start"))
        self.horizontalLayout_3.addWidget(self.pushButton_start)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pushButton_start_2 = QtGui.QPushButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_start_2.setIcon(icon2)
        self.pushButton_start_2.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_start_2.setObjectName(_fromUtf8("pushButton_start_2"))
        self.verticalLayout.addWidget(self.pushButton_start_2)
        self.pushButton_stop = QtGui.QPushButton(self.centralwidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_stop.setIcon(icon3)
        self.pushButton_stop.setObjectName(_fromUtf8("pushButton_stop"))
        self.verticalLayout.addWidget(self.pushButton_stop)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_4.setEnabled(False)
        self.pushButton_4.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_4.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/3.png")), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/3.png")), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.pushButton_4.setIcon(icon4)
        self.pushButton_4.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_4.setCheckable(False)
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.pushButton_add_to_vlc = QtGui.QPushButton(self.centralwidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_add_to_vlc.setIcon(icon5)
        self.pushButton_add_to_vlc.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_add_to_vlc.setObjectName(_fromUtf8("pushButton_add_to_vlc"))
        self.verticalLayout_2.addWidget(self.pushButton_add_to_vlc)
        self.pushButton_add_and_play = QtGui.QPushButton(self.centralwidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/play.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_add_and_play.setIcon(icon6)
        self.pushButton_add_and_play.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_add_and_play.setObjectName(_fromUtf8("pushButton_add_and_play"))
        self.verticalLayout_2.addWidget(self.pushButton_add_and_play)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkBox_cleantmp = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_cleantmp.setChecked(True)
        self.checkBox_cleantmp.setObjectName(_fromUtf8("checkBox_cleantmp"))
        self.gridLayout.addWidget(self.checkBox_cleantmp, 1, 3, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_8.addWidget(self.label_9)
        self.comboBox_quality = QtGui.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("WenQuanYi Micro Hei Mono"))
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_quality.setFont(font)
        self.comboBox_quality.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.comboBox_quality.setObjectName(_fromUtf8("comboBox_quality"))
        self.horizontalLayout_8.addWidget(self.comboBox_quality)
        self.gridLayout.addLayout(self.horizontalLayout_8, 0, 3, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_6.addWidget(self.label_5)
        self.lcdNumber = QtGui.QLCDNumber(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setNumDigits(4)
        self.lcdNumber.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber.setProperty("value", 0.0)
        self.lcdNumber.setProperty("intValue", 0)
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.horizontalLayout_6.addWidget(self.lcdNumber)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_6.addWidget(self.label_7)
        self.gridLayout.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_7.addWidget(self.label_6)
        self.lcdNumber_2 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_2.setNumDigits(4)
        self.lcdNumber_2.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_2.setObjectName(_fromUtf8("lcdNumber_2"))
        self.horizontalLayout_7.addWidget(self.lcdNumber_2)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_7.addWidget(self.label_8)
        self.gridLayout.addLayout(self.horizontalLayout_7, 1, 1, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.doubleSpinBox_segsize = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_segsize.setSingleStep(0.2)
        self.doubleSpinBox_segsize.setObjectName(_fromUtf8("doubleSpinBox_segsize"))
        self.horizontalLayout_4.addWidget(self.doubleSpinBox_segsize)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_5.addWidget(self.line)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.spinBox_segments = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_segments.setObjectName(_fromUtf8("spinBox_segments"))
        self.horizontalLayout_5.addWidget(self.spinBox_segments)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 1, 1, 1)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 0, 2, 1, 1)
        self.horizontalLayout_10.addLayout(self.gridLayout)
        self.label_drop_url = QtGui.QLabel(self.centralwidget)
        self.label_drop_url.setEnabled(True)
        self.label_drop_url.setMinimumSize(QtCore.QSize(20, 0))
        self.label_drop_url.setMaximumSize(QtCore.QSize(99, 16777215))
        self.label_drop_url.setAcceptDrops(True)
        self.label_drop_url.setFrameShape(QtGui.QFrame.Box)
        self.label_drop_url.setFrameShadow(QtGui.QFrame.Raised)
        self.label_drop_url.setLineWidth(2)
        self.label_drop_url.setMidLineWidth(2)
        self.label_drop_url.setAlignment(QtCore.Qt.AlignCenter)
        self.label_drop_url.setWordWrap(True)
        self.label_drop_url.setMargin(3)
        self.label_drop_url.setObjectName(_fromUtf8("label_drop_url"))
        self.horizontalLayout_10.addWidget(self.label_drop_url)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.tableWidget = QtGui.QTableWidget(self.centralwidget)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 150))
        self.tableWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.listWidget_process = QtGui.QListWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_process.sizePolicy().hasHeightForWidth())
        self.listWidget_process.setSizePolicy(sizePolicy)
        self.listWidget_process.setMinimumSize(QtCore.QSize(0, 12))
        self.listWidget_process.setMaximumSize(QtCore.QSize(16777215, 90))
        self.listWidget_process.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.listWidget_process.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.listWidget_process.setResizeMode(QtGui.QListView.Adjust)
        self.listWidget_process.setViewMode(QtGui.QListView.IconMode)
        self.listWidget_process.setObjectName(_fromUtf8("listWidget_process"))
        self.verticalLayout_3.addWidget(self.listWidget_process)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 583, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_Setting = QtGui.QMenu(self.menubar)
        self.menu_Setting.setObjectName(_fromUtf8("menu_Setting"))
        self.menuDestination_folder = QtGui.QMenu(self.menu_Setting)
        self.menuDestination_folder.setObjectName(_fromUtf8("menuDestination_folder"))
        self.menuLanguage = QtGui.QMenu(self.menu_Setting)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/language.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuLanguage.setIcon(icon7)
        self.menuLanguage.setObjectName(_fromUtf8("menuLanguage"))
        self.menu_About = QtGui.QMenu(self.menubar)
        self.menu_About.setObjectName(_fromUtf8("menu_About"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menuJoin_Video = QtGui.QMenu(self.menubar)
        self.menuJoin_Video.setObjectName(_fromUtf8("menuJoin_Video"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_Save_Setting = QtGui.QAction(MainWindow)
        self.action_Save_Setting.setObjectName(_fromUtf8("action_Save_Setting"))
        self.actionAbout_me = QtGui.QAction(MainWindow)
        self.actionAbout_me.setObjectName(_fromUtf8("actionAbout_me"))
        self.actionOpen_vdl_file = QtGui.QAction(MainWindow)
        self.actionOpen_vdl_file.setObjectName(_fromUtf8("actionOpen_vdl_file"))
        self.actionOpen_URL = QtGui.QAction(MainWindow)
        self.actionOpen_URL.setObjectName(_fromUtf8("actionOpen_URL"))
        self.actionOpen_URL_from_clipboard = QtGui.QAction(MainWindow)
        self.actionOpen_URL_from_clipboard.setObjectName(_fromUtf8("actionOpen_URL_from_clipboard"))
        self.actionCurrent_folder = QtGui.QAction(MainWindow)
        self.actionCurrent_folder.setObjectName(_fromUtf8("actionCurrent_folder"))
        self.actionChange_folder = QtGui.QAction(MainWindow)
        self.actionChange_folder.setObjectName(_fromUtf8("actionChange_folder"))
        self.action_Load_Setting = QtGui.QAction(MainWindow)
        self.action_Load_Setting.setObjectName(_fromUtf8("action_Load_Setting"))
        self.actionOpen_folder = QtGui.QAction(MainWindow)
        self.actionOpen_folder.setObjectName(_fromUtf8("actionOpen_folder"))
        self.actionJoin_Now = QtGui.QAction(MainWindow)
        self.actionJoin_Now.setObjectName(_fromUtf8("actionJoin_Now"))
        self.actionEnglish = QtGui.QAction(MainWindow)
        self.actionEnglish.setObjectName(_fromUtf8("actionEnglish"))
        self.actionTraditional_Chinese = QtGui.QAction(MainWindow)
        self.actionTraditional_Chinese.setObjectName(_fromUtf8("actionTraditional_Chinese"))
        self.actionSimplified_Chinese = QtGui.QAction(MainWindow)
        self.actionSimplified_Chinese.setObjectName(_fromUtf8("actionSimplified_Chinese"))
        self.actionJapanese = QtGui.QAction(MainWindow)
        self.actionJapanese.setObjectName(_fromUtf8("actionJapanese"))
        self.actionOpen_tr_file = QtGui.QAction(MainWindow)
        self.actionOpen_tr_file.setObjectName(_fromUtf8("actionOpen_tr_file"))
        self.actionVisit_my_blogger = QtGui.QAction(MainWindow)
        self.actionVisit_my_blogger.setObjectName(_fromUtf8("actionVisit_my_blogger"))
        self.actionVisit_github_page = QtGui.QAction(MainWindow)
        self.actionVisit_github_page.setObjectName(_fromUtf8("actionVisit_github_page"))
        self.menuDestination_folder.addAction(self.actionCurrent_folder)
        self.menuDestination_folder.addAction(self.actionChange_folder)
        self.menuDestination_folder.addAction(self.actionOpen_folder)
        self.menuLanguage.addAction(self.actionEnglish)
        self.menuLanguage.addAction(self.actionTraditional_Chinese)
        self.menuLanguage.addAction(self.actionSimplified_Chinese)
        self.menuLanguage.addAction(self.actionJapanese)
        self.menu_Setting.addAction(self.menuDestination_folder.menuAction())
        self.menu_Setting.addSeparator()
        self.menu_Setting.addAction(self.action_Load_Setting)
        self.menu_Setting.addAction(self.action_Save_Setting)
        self.menu_Setting.addSeparator()
        self.menu_Setting.addAction(self.menuLanguage.menuAction())
        self.menu_About.addAction(self.actionVisit_my_blogger)
        self.menu_About.addAction(self.actionVisit_github_page)
        self.menu_About.addAction(self.actionAbout_me)
        self.menu_File.addAction(self.actionOpen_vdl_file)
        self.menu_File.addAction(self.actionOpen_URL)
        self.menu_File.addAction(self.actionOpen_URL_from_clipboard)
        self.menuJoin_Video.addAction(self.actionJoin_Now)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Setting.menuAction())
        self.menubar.addAction(self.menuJoin_Video.menuAction())
        self.menubar.addAction(self.menu_About.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButton_start, self.pushButton_start_2)
        MainWindow.setTabOrder(self.pushButton_start_2, self.pushButton_add_and_play)
        MainWindow.setTabOrder(self.pushButton_add_and_play, self.doubleSpinBox_segsize)
        MainWindow.setTabOrder(self.doubleSpinBox_segsize, self.spinBox_segments)
        MainWindow.setTabOrder(self.spinBox_segments, self.comboBox_quality)
        MainWindow.setTabOrder(self.comboBox_quality, self.checkBox_cleantmp)
        MainWindow.setTabOrder(self.checkBox_cleantmp, self.tableWidget)
        MainWindow.setTabOrder(self.tableWidget, self.listWidget_process)
        MainWindow.setTabOrder(self.listWidget_process, self.pushButton_stop)
        MainWindow.setTabOrder(self.pushButton_stop, self.pushButton_add_to_vlc)
        MainWindow.setTabOrder(self.pushButton_add_to_vlc, self.lineEdit_title)
        MainWindow.setTabOrder(self.lineEdit_title, self.pushButton_4)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "BBQ Video Downloader", None))
        self.label.setText(_translate("MainWindow", "Title:", None))
        self.pushButton_start.setText(_translate("MainWindow", "Fetch Info", None))
        self.pushButton_start_2.setText(_translate("MainWindow", "Start download", None))
        self.pushButton_stop.setText(_translate("MainWindow", "Stop", None))
        self.pushButton_add_to_vlc.setText(_translate("MainWindow", "Add to VLC", None))
        self.pushButton_add_and_play.setText(_translate("MainWindow", "Add && PLAY", None))
        self.checkBox_cleantmp.setText(_translate("MainWindow", "Clean temp files", None))
        self.label_9.setText(_translate("MainWindow", "Quality:", None))
        self.label_5.setText(_translate("MainWindow", "Time spent:", None))
        self.label_7.setText(_translate("MainWindow", "s", None))
        self.label_6.setText(_translate("MainWindow", "Time left:", None))
        self.label_8.setText(_translate("MainWindow", "s", None))
        self.label_2.setText(_translate("MainWindow", "Segment size:", None))
        self.label_3.setText(_translate("MainWindow", "MB", None))
        self.label_4.setText(_translate("MainWindow", "Threads:", None))
        self.label_drop_url.setText(_translate("MainWindow", "Drop URL here", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Filename", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Size", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Time", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "%", None))
        self.menu_Setting.setTitle(_translate("MainWindow", "&Setting", None))
        self.menuDestination_folder.setTitle(_translate("MainWindow", "Destination folder", None))
        self.menuLanguage.setTitle(_translate("MainWindow", "Language", None))
        self.menu_About.setTitle(_translate("MainWindow", "&About", None))
        self.menu_File.setTitle(_translate("MainWindow", "&File", None))
        self.menuJoin_Video.setTitle(_translate("MainWindow", "Join Video", None))
        self.action_Save_Setting.setText(_translate("MainWindow", "&Save Setting", None))
        self.actionAbout_me.setText(_translate("MainWindow", "About...", None))
        self.actionOpen_vdl_file.setText(_translate("MainWindow", "Open &vdl file", None))
        self.actionOpen_vdl_file.setToolTip(_translate("MainWindow", "Open vdl file", None))
        self.actionOpen_URL.setText(_translate("MainWindow", "Open URL", None))
        self.actionOpen_URL_from_clipboard.setText(_translate("MainWindow", "Open URL from clipboard", None))
        self.actionCurrent_folder.setText(_translate("MainWindow", "current folder", None))
        self.actionChange_folder.setText(_translate("MainWindow", "change folder...", None))
        self.action_Load_Setting.setText(_translate("MainWindow", "&Load Setting", None))
        self.actionOpen_folder.setText(_translate("MainWindow", "open folder", None))
        self.actionJoin_Now.setText(_translate("MainWindow", "Join Now!", None))
        self.actionEnglish.setText(_translate("MainWindow", "English", None))
        self.actionTraditional_Chinese.setText(_translate("MainWindow", "Traditional Chinese(繁体中文)", None))
        self.actionSimplified_Chinese.setText(_translate("MainWindow", "Simplified Chinese(简体中文)", None))
        self.actionJapanese.setText(_translate("MainWindow", "Japanese(日本語)", None))
        self.actionOpen_tr_file.setText(_translate("MainWindow", "open tr file...", None))
        self.actionVisit_my_blogger.setText(_translate("MainWindow", "Visit my blogger", None))
        self.actionVisit_github_page.setText(_translate("MainWindow", "Visit github page", None))

import iconfile_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

